# Generated by Django 3.0.3 on 2020-06-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_blogcontent1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogContent',
        ),
    ]
