# Generated by Django 3.0.3 on 2020-06-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0008_publishuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent11',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
